global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'auth_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth_service:8000']

  - job_name: 'celery_worker_service'
    metrics_path: /metrics
    bearer_token_file: /etc/prometheus/secrets/celery_worker_metrics.jwt
    static_configs:
      - targets: ['celery_worker_service:9000']
