global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'auth_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth_service:8000']

  - job_name: 'orders_service'
    metrics_path: /metrics
    bearer_token_file: /etc/prometheus/secrets/orders_metrics_jwt
    static_configs:
      - targets: ['orders_service:8000']
